# Generated by Django 2.2.7 on 2019-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=100)),
                ('car_model', models.CharField(default='', max_length=100)),
                ('trim', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(default='', max_length=100)),
                ('part_num', models.CharField(default='', max_length=100)),
                ('quantity', models.PositiveIntegerField(default='0')),
                ('price_each', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('price_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('link_part', models.TextField(default='')),
                ('notes', models.CharField(default='', max_length=500)),
                ('image_url', models.CharField(default='', max_length=512)),
                ('installed', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete='CASCADE', related_name='parts', to='carmod.Car')),
                ('category', models.ForeignKey(on_delete='CASCADE', related_name='parts', to='carmod.Category')),
            ],
        ),
    ]
