# Generated by Django 2.2.7 on 2019-11-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='car',
        ),
        migrations.AddField(
            model_name='category',
            name='car',
            field=models.ForeignKey(default='', on_delete='CASCADE', related_name='categorys', to='carmod.Car'),
        ),
    ]
