# Generated by Django 2.2.7 on 2019-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0003_auto_20191106_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='link_part',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
