# Generated by Django 2.2.7 on 2019-11-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0004_auto_20191106_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='car',
        ),
    ]
