# Generated by Django 2.2.7 on 2019-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0005_remove_part_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
