# Generated by Django 2.2.7 on 2019-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0006_auto_20191107_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
