# Generated by Django 2.2.7 on 2019-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0007_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='part',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
