# Generated by Django 2.2.7 on 2019-11-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0014_auto_20191107_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
