# Generated by Django 2.2.7 on 2019-11-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0015_auto_20191107_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='test',
            field=models.CharField(default='', max_length=100),
        ),
    ]
