# Generated by Django 2.2.7 on 2019-11-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmod', '0016_part_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='test',
        ),
    ]
